version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_nest
    restart: always
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: bfreedom_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_nest
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
        - postgres

volumes:
  postgres_data:
    driver: local